%close all hidden;
%clear all


randn('state',0);
rand('state',0);

height = 2/3;
set(0,...
'defaultfigureposition',[180 100 800 800*height],...
'defaultaxeslinewidth',1,...
'defaultaxesfontsize',18,...
'defaultaxesfontname','Arial',...
'defaultlinelinewidth',2,...
'defaultpatchlinewidth',1,...
'defaultlinemarkersize',10,...
'defaulttextinterpreter','latex');


